### ISSUE TITLE
Re-add UI loading from m2demo/iw4lan folder

### ISSUE THREAD

**Issue by win32re** [twizre/iw4lan#2]

**Comment by jdmplur** [comment]
How is it going?

**Comment by win32re** [comment]
Fine, thanks.

**Comment by win32re** [comment]
@jdmplur A new version with the UI loading feature will be available on the website once I fix the crash which occurs when the game starts.

**Comment by jdmplur** [comment]
@win32re I can't wait for it to be released. I love the work your doing.

**Comment by win32re** [comment]
@jdmplur I'm just adding/removing stuff, NTAuthority is the real author of all IW4M-based projects.

**Comment by jdmplur** [comment]
@win32re Ok then all thanks goes to NTAuthority. Are you the only one working on this client?

**Comment by win32re** [comment]
Yep. You can see who helped [
https://github.com/twizre/iw4lan/graphs/contributors](here).

**Comment by win32re** [comment]
Yep. You can see who helped [here](https://github.com/twizre/iw4lan/graphs/contributors).

**Comment by jdmplur** [comment]
@win32re How much longer till the release?

**Comment by win32re** [comment]
@jdmplur Released: https://github.com/twizre/iw4lan/releases/download/r66/iw4lan-r66.zip

**Comment by jdmplur** [comment]
So what does this release actually do?

**Comment by win32re** [comment]
@jdmplur It loads custom menus from 'iw4lan' folder which is basically a renamed 'm2demo' folder.
